### ISSUE TITLE
ImportError in virtualnv

### ISSUE THREAD

**Issue by nkman** [pravj/lisense#1]
### Running this in Virtual Python Environment builder

``` sh
$ lisense list
```
### Gives the following error

``` sh
$ lisense list
Traceback (most recent call last):
  File "/home/nkman/Desktop/sample_pip/v/bin/lisense", line 9, in <module>
    load_entry_point('lisense==1.0.0', 'console_scripts', 'lisense')()
  File "/home/nkman/Desktop/sample_pip/v/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/nkman/Desktop/sample_pip/v/local/lib/python2.7/site-packages/pkg_resources.py", line 2431, in load_entry_point
    return ep.load()
  File "/home/nkman/Desktop/sample_pip/v/local/lib/python2.7/site-packages/pkg_resources.py", line 2147, in load
    ['__name__'])
  File "/home/nkman/Desktop/sample_pip/v/local/lib/python2.7/site-packages/lisense/lisense.py", line 19, in <module>
    from parser.parser import ArgumentParser
  File "/home/nkman/Desktop/sample_pip/v/local/lib/python2.7/site-packages/lisense/parser/parser.py", line 12, in <module>
    from ..commands.guide import generate_guide
  File "/home/nkman/Desktop/sample_pip/v/local/lib/python2.7/site-packages/lisense/commands/guide.py", line 11, in <module>
    from yaml import load
ImportError: No module named yaml
```

**Comment by nkman** [comment]
### Resolved after installing pyyaml via pip though

``` sh
$ pip install pyyaml
```

**Comment by pravj** [comment]
But don't you think it should have installed `pyyaml` on its own?

**Comment by pravj** [comment]
Aha! gotcha.

I missed adding it in required package in the [setup file](https://github.com/pravj/lisense/blob/master/setup.py#L22).

``` python
install_requires=['docopt', 'jinja2', 'xtermcolor']
```

Thanks for the catch, adding it now.

**Comment by pravj** [comment]
Can you try now. Fresh? :smile:

**Comment by pravj** [comment]
Or maybe I missed it again. This time in requirements.txt. Instead of asking you, I should have tested on my own.

**Comment by nkman** [comment]
Lol.

**Comment by pravj** [comment]
OK! it's working, will add 'pyyaml' in requirements.txt in some next commits then.

Thanks for notifying.
